#!/bin/bash

# Copyright 2022 Jamie Woods, Insanity Radio - all rights reserved.
# See LICENSE

usage() {
	echo "Usage:"
	echo "  $0 tx --host 127.0.0.1 --port 3600 --source 'autoaudiosrc' [--redundancy 0-2]"
	echo "  $0 rx --host 127.0.0.1 --port 3600 --sink 'autoaudiosink' [--latency 200]"
	exit 1;
}

HOST=127.0.0.1
BIND=0.0.0.0
PORT=3600
SOURCE=autoaudiosrc
SINK=autoaudiosink
SAMPLE_RATE=48000
REDUNDANCY=0
LATENCY=200
GST_LAUNCH="/usr/bin/nice -n -20 gst-launch-1.0"
TCP=

while [[ $# -gt 0 ]]; do
	case $1 in
		tx)
			[[ $MODE ]] && (echo Mode already set; exit 1)
			MODE=tx
			shift ;;
		rx)
			[[ $MODE ]] && (echo Mode already set; exit 1)
			MODE=rx
			shift ;;
		--host)
			HOST="$2"
			shift; shift ;;
		--port)
			PORT="$2"
			shift; shift ;;
		--bind)
			BIND="$2"
			shift; shift ;;
		--source)
			SOURCE="$2"
			shift; shift ;;
		--sink)
			SINK="$2"
			shift; shift ;;
		--latency)
			LATENCY="$2"
			shift; shift ;;
		--redundancy)
			REDUNDANCY="$2"
			shift; shift ;;
		--gst-launch)
			GST_LAUNCH="$2"
			shift; shift ;;
		--sample-rate)
			SAMPLE_RATE="$2"
			shift; shift ;;
		--tcp)
			TCP=1
			DISTANCE="0"
			shift ;;
		-*|--*)
			echo "Unknown option $1"
			usage
			exit 1 ;;
		*)
			;;
	esac
done

[[ $MODE ]] || usage

trap_ctrlC() {
    echo "Press CTRL-C again to exit. Restarting in 1 second"
    sleep 1 || exit 1
}

trap trap_ctrlC SIGINT SIGTERM

echo "**  Starting GStreamer"
echo

while true; do
	if [[ $MODE == "tx" ]]; then 

		if [[ $TCP == 1 ]]; then
			SINK="rtpL16pay pt=96 ! rtpstreampay ! tcpserversink port=$PORT host=$BIND"
		else
			SINK="rtpL16pay mtu=1023 pt=103 ! rtpredenc distance=$REDUNDANCY pt=122 ! udpsink host=$HOST port=$PORT"
		fi

		$GST_LAUNCH $SOURCE do-timestamp=true \
			! audioconvert ! audioresample ! queue \
			! audio/x-raw,format=S16BE,channels=2,rate=$SAMPLE_RATE \
			! $SINK

	elif [[ $MODE == "rx" ]]; then

		if [[ $TCP == 1 ]]; then 
			SOURCE="tcpclientsrc host=$HOST port=$PORT do-timestamp=true \
				! application/x-rtp-stream,clock-rate=$SAMPLE_RATE,media=audio,payload=96,encoding-name=L16 \
				! rtpstreamdepay \
				! rtpstorage size-time=220000000 \
				! rtpjitterbuffer latency=$LATENCY"
		else
			SOURCE="udpsrc uri=udp://$HOST:$PORT caps=\"application/x-rtp,payload=103\" \
				! rtpreddec pt=122 \
				! rtpstorage size-time=220000000 ! application/x-rtp, payload=103, media=audio \
				! rtpjitterbuffer do-lost=1 latency=$LATENCY"
		fi

		echo $SOURCE
		$GST_LAUNCH $SOURCE \
			! rtpL16depay \
			! rawaudioparse format=pcm pcm-format=s16be sample-rate=$SAMPLE_RATE num-channels=2 \
			! audioconvert ! queue ! audiorate ! queue \
			! $SINK

	else
		usage
	fi

	echo
	echo "**  Restarting GStreamer"
	echo

	sleep 0.25
done
